config/routes.rb
Rails.application.routes.draw do

  root 'pins#index'

  devise_for :users

  resources :pins

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user

  has_attached_file :image, styles: {medium: '300x300>'}
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  # Title must be specified
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Register custom flash types
  # :error and :notice already exist
  add_flash_types :success
  add_flash_types :alert
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy]

  def index
    @pins = Pin.all.order('created_at DESC')
  end

  def show
    # Handled by the before action
  end

  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to root_url, success:'Successfully created the pin!'
    else
      render 'new'
    end
  end

  def edit
    # Handled by the before action
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, success: 'The pin was successfully updated!'
    else
      render 'edit'
    end
  end

  def destroy
    if @pin.destroy
      redirect_to root_url, success: 'Successfully deleted the pin!'
    else
      redirect_to :back, error: 'There was a problem deleting your pin!'
    end
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def flash_class_for flash_type
    { success: 'flash-success', error: 'flash-error', alert: 'flash-alert', notice: 'flash-info' }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_nav.html.haml
-# Dropdown shown only when user is logged in.
%ul{ id: 'user-dropdown-menu', class: 'dropdown-content' }
  %li= link_to 'New Pin', new_pin_url
  %li.divider
  %li= link_to 'Account settings', edit_user_registration_url
  %li= link_to 'Sign out', destroy_user_session_url, method: :delete

%nav
  .nav-wrapper
    = link_to 'Pipapi', root_url, class: 'brand-logo waves-effect waves-light'
    %ul{ id: 'nav-mobile', class: 'right hide-on-med-and-down' }

      -# Show these menu-items only if the user is signed-in
      - if user_signed_in?
        %li
          %a(class="dropdown-button waves-effect waves-light" href="#!" data-activates="user-dropdown-menu")
            = current_user.email
            %i.material-icons.right arrow_drop_down
      - else
        %li= link_to 'Sign up', '#signUpModal', {:class => 'waves-effect waves-light modal-trigger'}
        %li= link_to 'Sign in', '#signInModal', {:class => 'waves-effect waves-light modal-trigger'}

app/views/layouts/_signInModal.haml
#signInModal.modal
  = simple_form_for(:user, :url => user_session_path) do |f|
    .modal-content
      %h2 Log in

      .row
        .col.s12

          .row
            .s12
              = f.input :email, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix person
                = f.label :email, 'Email'
                = f.input_field :email, required: false, autofocus: true, class: 'validate'

          .row
            .s12
              = f.input :password , label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix lock
                = f.label :password, 'Password'
                = f.input_field :password , required: false

          .row
            .s12
              = f.input :remember_me, as: :boolean if devise_mapping.rememberable?

    .modal-footer
      %button{:class => 'btn waves-effect waves-light', :type => 'submit', :name => 'commit'}
        %i.material-icons.right send
        Log in

app/views/layouts/_signUpModal.haml
#signUpModal.modal
  = simple_form_for(:user, :url => user_registration_path) do |f|
    .modal-content
      %h2 Sign up

      .row
        .col.s12

          = f.error_notification

          .row
            .s12
              = f.input :email, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix person
                = f.label :email, 'Email'
                = f.input_field :email, required: true, autofocus: true, class: 'validate'

          .row
            .s12
              = f.input :password , label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix lock
                = f.label :password, 'Password'
                = f.input_field :password , required: true, hint: ("#{@minimum_password_length} characters minimum" if @validatable)

          .row
            .s12
              = f.input :password_confirmation, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix lock
                = f.label :password_confirmation, 'Confirm password'
                = f.input_field :password_confirmation, required: true

    .modal-footer
      %button{:class => 'btn waves-effect waves-light', :type => 'submit', :name => 'commit'}
        %i.material-icons.right send
        Sign Up

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= (yield(:title) + ' :: ' unless yield(:title).blank?).to_s + 'Pipapi - Pinboard'
    %meta{ :content => 'A pinboard app I created for learning purposes.', :name => 'description' }
    %meta{ :content => 'tomschillemans@gmail.com', :name => 'author' }
    %link{ :href => 'https://fonts.googleapis.com/icon?family=Material+Icons', :rel => 'stylesheet' }
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false
    = javascript_include_tag 'application', 'data-turbolinks-track' => false
    = csrf_meta_tags

  %body
    = render partial: 'shared/flash_messages', flash: flash

    = render 'shared/nav'

    %div{:class => ('container' unless current_page?(root_path))}
      - if !user_signed_in?
        = render 'shared/sign_in_modal'
        = render 'shared/sign_up_modal'

      = yield

app/views/pins/_form.html.haml
= simple_form_for @pin, html: {multipart: true} do |f|
  - if @pin.errors.any?
    #errors
      %h2
        = pluralize(@pin.errors.count, 'error')
        prevented this Pin from being saved
        %ul
          - @pin.errors.full_messages.each do |msg|
            %li= msg


  .row
    .col.s12
      .card
        .card-content

          .row
            .s12
              -# TODO: Figure out a way to style this accordingly to MaterialCSS
              = f.input :image

          .row
            .col.s12
              = f.input :title, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix text_format
                - if @pin.title.present?
                  = f.label :title, 'Title', :class => 'active'
                  = f.input_field :title, :value => @pin.title, :class => 'validate'
                - else
                  = f.label :title, 'Title'
                  = f.input_field :title, :class => 'validate'

          .row
            .col.s12
              = f.input :description, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix message
                - if @pin.description.present?
                  = f.label :description, 'Description', :class => 'active'
                  = f.input_field :description, :value => @pin.description, :class => 'validate materialize-textarea'
                - else
                  = f.label :description, 'Description'
                  = f.input_field :description, :class => 'validate materialize-textarea'
        .card-action
          %button{:class => 'btn waves-effect waves-light', :type => 'submit', :name => 'commit'}
            %i.material-icons.right send
            Create Pin

          =link_to :back, :class => 'right btn waves-effect waves-light white-text red' do
            %i.material-icons.left undo
            Cancel

app/views/pins/edit.html.haml
%h1 Edit Pin
= image_tag @pin.image.url(:medium)
= render 'form'

app/views/pins/index.html.haml
= content_for(:title, 'Home')

#pins.transitions-enabled
  - @pins.each do |pin|
    .box
      .card
        .card-image.waves-effect.waves-block.waves-light
          = link_to (image_tag pin.image.url), pin

        - if pin.description
          %span.card-title.black-text= pin.title
          .card-content
            %p= pin.description

app/views/pins/new.html.haml
%h1 New Pin

= render 'form'

app/views/pins/show.html.haml
= content_for :title, "#{@pin.title}"

.row
  .col.s12
    .card.black-text
      .card-image
        = image_tag @pin.image.url

      .card-content
        %span.card-title.black-text= @pin.title
        %p= @pin.description

      .card-action

        = link_to 'Home', root_path, class: 'waves-effect waves-light btn white-text'

        = link_to edit_pin_path, class: 'waves-effect waves-light btn white-text' do
          Edit
          %i.material-icons.right edit

        = link_to pin_path, method: :delete, data: {confirm: 'Are you sure?'},
            class: 'waves-effect waves-light btn red white-text' do
          Delete
          %i.material-icons.right delete

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
    <div id="flash_wrapper">
        <div class="flash <%= flash_class_for(type) %>">
          <%= message %>
        </div>
    </div>
<% end %>

app/views/shared/_nav.haml
-# Dropdown shown only when user is logged in.
%ul{ id: 'user-dropdown-menu', class: 'dropdown-content' }
  %li= link_to 'New Pin', new_pin_url
  %li.divider
  %li= link_to 'Account settings', edit_user_registration_url
  %li= link_to 'Sign out', destroy_user_session_url, method: :delete

%nav
  .nav-wrapper
    = link_to 'Pipapi', root_url, class: 'brand-logo waves-effect waves-light'
    %ul{ id: 'nav-mobile', class: 'right hide-on-med-and-down' }

      -# Show these menu-items only if the user is signed-in
      - if user_signed_in?
        %li
          %a(class="dropdown-button waves-effect waves-light" href="#!" data-activates="user-dropdown-menu")
            = current_user.email
            %i.material-icons.right arrow_drop_down
      - else
        %li= link_to 'Sign up', '#signUpModal', {:class => 'waves-effect waves-light modal-trigger'}
        %li= link_to 'Sign in', '#signInModal', {:class => 'waves-effect waves-light modal-trigger'}

app/views/shared/_sign_in_modal.haml
#signInModal.modal
  = simple_form_for(:user, :url => user_session_path) do |f|
    .modal-content
      %h2 Log in

      .row
        .col.s12

          .row
            .s12
              = f.input :email, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix person
                = f.label :email, 'Email'
                = f.input_field :email, required: false, autofocus: true, class: 'validate'

          .row
            .s12
              = f.input :password , label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix lock
                = f.label :password, 'Password'
                = f.input_field :password , required: false

          .row
            .s12
              = f.input :remember_me, as: :boolean if devise_mapping.rememberable?

    .modal-footer
      %button{:class => 'btn waves-effect waves-light', :type => 'submit', :name => 'commit'}
        %i.material-icons.right send
        Log in

app/views/shared/_sign_up_modal.haml
#signUpModal.modal
  = simple_form_for(:user, :url => user_registration_path) do |f|
    .modal-content
      %h2 Sign up

      .row
        .col.s12

          = f.error_notification

          .row
            .s12
              = f.input :email, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix person
                = f.label :email, 'Email'
                = f.input_field :email, required: true, autofocus: true, class: 'validate'

          .row
            .s12
              = f.input :password , label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix lock
                = f.label :password, 'Password'
                = f.input_field :password , required: true, hint: ("#{@minimum_password_length} characters minimum" if @validatable)

          .row
            .s12
              = f.input :password_confirmation, label: false, :wrapper => :vertical_form do
                %i.material-icons.prefix lock
                = f.label :password_confirmation, 'Confirm password'
                = f.input_field :password_confirmation, required: true

    .modal-footer
      %button{:class => 'btn waves-effect waves-light', :type => 'submit', :name => 'commit'}
        %i.material-icons.right send
        Sign Up